# Generated by Django 5.1 on 2024-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaswitch',
            name='em_uso',
            field=models.BooleanField(default=False),
        ),
    ]
