# Generated by Django 5.1 on 2024-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0002_portaswitch_em_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
