# Generated by Django 5.1 on 2024-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0003_switch_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='modelo',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
