# Generated by Django 5.1 on 2024-08-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='contato',
            field=models.CharField(default='Contato padrão', max_length=100),
            preserve_default=False,
        ),
    ]
