# Generated by Django 5.1 on 2024-08-31 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_chamado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='local',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.departamento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.local'),
        ),
    ]
