# Generated by Django 5.1 on 2024-09-07 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_chamado_descricao_tecnica_chamado_encerrado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='encerrado_em',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='encerrado_por',
        ),
        migrations.AddField(
            model_name='chamado',
            name='fechado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario_fechamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='nr_patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
