# Generated by Django 5.1 on 2024-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_rename_fechado_em_chamado_encerrado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='numero',
            field=models.CharField(default=' ', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chamado',
            name='tempo_resposta',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
