# Generated by Django 5.1 on 2024-09-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_chamado_numero_chamado_tempo_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='chamado',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
