# Generated by Django 5.1 on 2024-09-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_sequenciachamado_alter_chamado_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(choices=[('COMPUTADOR', 'Computador'), ('IMPRESSORA', 'Impressora'), ('TELEFONE', 'Telefone'), ('MUDANÇA', 'Mudança'), ('OUTROS', 'outros')], max_length=100),
        ),
    ]
