# Generated by Django 5.1 on 2024-09-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_alter_chamado_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(choices=[('Computador', 'Computador'), ('Impressora', 'Impressora'), ('Telefone', 'Telefone'), ('Mudança', 'Mudança'), ('Outros', 'outros')], max_length=100),
        ),
    ]
