# Generated by Django 5.1 on 2024-09-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('numero_equipamento', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
            ],
        ),
    ]
