# Generated by Django 5.1 on 2024-11-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0003_patrimonio_tem_headset_patrimonio_tem_webcam_and_more'),
        ('utilitarios', '0002_ramal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThinClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('numero_monitor', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=100)),
                ('patrimonio', models.ForeignKey(limit_choices_to={'tipo': 'thinclient'}, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
            ],
        ),
    ]
