# Generated by Django 5.1 on 2024-11-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_alter_chamado_titulo'),
        ('patrimonios', '0003_patrimonio_tem_headset_patrimonio_tem_webcam_and_more'),
        ('utilitarios', '0003_thinclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinclient',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.local'),
        ),
        migrations.AlterField(
            model_name='thinclient',
            name='numero_monitor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='thinclient',
            name='patrimonio',
            field=models.ForeignKey(limit_choices_to={'tipo': 'THINCLIENT'}, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio', verbose_name='Número de Patrimônio'),
        ),
        migrations.AlterField(
            model_name='thinclient',
            name='senha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='thinclient',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
