# Generated by Django 5.1.5 on 2025-01-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_alter_chamado_titulo'),
        ('utilitarios', '0004_alter_thinclient_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.departamento'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.local'),
        ),
    ]
