# Generated by Django 5.1.5 on 2025-01-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0003_patrimonio_tem_headset_patrimonio_tem_webcam_and_more'),
        ('utilitarios', '0005_impressora_departamento_alter_impressora_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='patrimonio',
            field=models.ForeignKey(limit_choices_to=models.Q(('tipo', 'COMPUTADOR'), ('tipo', 'VOIP'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio', verbose_name='Número de Patrimônio'),
        ),
    ]
