# Generated by Django 5.1.5 on 2025-01-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_alter_chamado_titulo'),
        ('utilitarios', '0006_alter_ramal_patrimonio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinclient',
            name='local',
        ),
        migrations.AddField(
            model_name='thinclient',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chamados.departamento'),
            preserve_default=False,
        ),
    ]
