# Generated by Django 5.1 on 2024-09-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0010_sequenciachamado_alter_chamado_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('CAMERA', 'Camera'), ('COMPUTADOR', 'Computador'), ('HEADSET', 'Headset'), ('IMPRESSORA', 'Impressora'), ('MONITOR', 'Monitor'), ('NOBREAK', 'Nobreak'), ('OUTROS', 'Outros'), ('RACK', 'Rack'), ('SWITCH', 'Switch'), ('TELEFONE', 'Telefone'), ('THINCLIENT', 'Thinclient'), ('WEBCAM', 'Webcam'), ('WIFI', 'Wifi')], max_length=20)),
                ('obs', models.CharField(max_length=50, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('memoria_ram', models.CharField(blank=True, max_length=50, null=True)),
                ('hd', models.CharField(blank=True, max_length=50, null=True)),
                ('processador', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_video', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.departamento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.local')),
            ],
        ),
    ]
