# Generated by Django 5.1 on 2024-09-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimonio',
            name='ip',
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='obs',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
