# Generated by Django 5.1 on 2024-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0002_remove_patrimonio_ip_alter_patrimonio_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='tem_headset',
            field=models.BooleanField(default=False, verbose_name='Possui Headset?'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='tem_webcam',
            field=models.BooleanField(default=False, verbose_name='Possui Webcam?'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='marca',
            field=models.CharField(max_length=50),
        ),
    ]
